services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/.env:/app/.env
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - TZ=Europe/Berlin
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

